name: ecoroute
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  dio: ^5.9.0
  either_dart: ^1.0.0
  firebase_analytics: ^12.0.1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^3.0.1
  geolocator: ^14.0.2
  get_it: ^8.2.0
  google_maps_flutter: ^2.13.1
  google_sign_in: ^5.1.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  location: ^8.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sentry_flutter: ^9.7.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
